### ISSUE TITLE
Design the Authentication mechanisms of Corpora

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#313]
**Deadline for Review: 2020-07-17**

[Authentication in Corpora and Cellxgene](https://docs.google.com/document/d/19cC_tH7DOHIYqojdo-6T9eTzPmoMkwrAj83Ozvqth8s/edit#heading=h.t849jh3lwzxu)

AuthN and AuthZ will be a shared service across the data portal and cellxgene. Will need to coordinate with the cellxgene team.

This ticket should culminate in a design doc approved by engineers on both efforts.

**Comment by brianraymor** [comment]
For M2 planning, there are pending design discussions in the 2020 plan related to how sharing capability url(s) may intersect with authentication:

- [Comment Thread](https://docs.google.com/document/d/13KbnfQVruyEp5JbeTbhelYejroqBHn2jtW0YbRnAx0I/edit?disco=AAAAGdWWktA)

- [Comment Thread](https://docs.google.com/document/d/13KbnfQVruyEp5JbeTbhelYejroqBHn2jtW0YbRnAx0I/edit?disco=AAAAGdWWks4)

**Comment by brianraymor** [comment]
**Capturing notes from design discussion:**

The 2020 plan will be updated to reflect the following changes. Registration is only required for two cases:

1. To submit and manage datasets
2. To create and persist user annotations or other user state

Registration is **NOT** required for consumers downloading datasets or viewing projects or data. 

For _Scientists who host pre-publication data on Corpora want their data to be private until their dataset has been peer reviewed so they have a chance to fix errors before the data are widely viewed._:

Submitters may request one [capability url](https://www.w3.org/TR/capability-urls/) (bearer token) per:
- submitted private project
- pending submission to revise a private submitted project

Capability urls are manually forwarded to reviewers or collaborators by the submitter to authorize access to a submitted private project or its pending revision. Note, this is coarse granularity because the capability url is per project/revision and not per reviewer/collaborator. No registration/authentication is required when a user is accessing a project with a capability url.

Projects owners may revoke a capability url at will. When a user navigates to a revoked url, there should be a “friendly” explanation offered rather than 404.

The capability url for a submitted private project must be constant unless the owner revokes the url. As revisions are submitted, the private project content changes but its capability url does not.

Once pending revisions are submitted, the capability url for the revision is automatically revoked. “It disappears”.

When a private project is published, the capability url for the private version must not be automagically revoked by the system. The owner is responsible for manually revoking “at the right time” which may be never. (There may be ongoing reviews of the private submission which would be interrupted)

**Comment by bmccandless** [comment]
Progress so far.  I've been coming up to speed with Auth0 by implementing a prototype for single page apps and one for regular web app.   There are a few more questions about how specifically to do the authentication challenge in a way that does not overly disrupt a user's progress in cellxgene.  I plan to do another experiment to resolve this.   By next Wednesday I plan to have a design document ready.

**Comment by bmccandless** [comment]
The first pass at the design document is complete, and In review
https://docs.google.com/document/d/19cC_tH7DOHIYqojdo-6T9eTzPmoMkwrAj83Ozvqth8s/edit?usp=sharing
