### ISSUE TITLE
Validate Seurat v3 RDS uploads

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#342]
Per the [Corpora Schema](https://docs.google.com/document/d/1_I2dnYuCTvO2yABR0FnLRnI8RnMhiASC5Ny4ZwDjsCI/edit#):

_Corpora requires submitted count matrices and associated metadata to be in one of three formats: AnnData, Loom, or a Seurat v3 RDS. Other formats are rejected. Each of these formats has a way to include metadata along with the count data, so a submission can be entirely contained within a single file._

Seurat files are handled via an R package which means that if we write our validators and any other tools in Python, we run into an issue with not being able to apply them to `.rds` files._

I can think of two options thus far:

1. Convert Seurat files to either Loom or H5AD and run the tools on the converted file. Pros is that we have a single toolkit, cons is that the conversion may or may not be successful and/lossy. Marcus mentioned that if you try to convert Seurat to Loom and haven't run `FindVariableGenes`, then the conversion will fail.

2. We duplicate the toolkits in R. We'll have to look into something like rpy2 to be able to unify the two flavors. Pros is that we will be able to natively handle Seurat objects, cons is that I haven't had great experience working with rpy2 in the past and we'll need to duplicate code to some extent in two languages. 

My proposal here is to investigate option 2 and figure out how buggy rpy2 actually is by implementing a PII checker (because the primary thing that is blocked is writing the validator which occurs before file format conversion) for Seurat and then making a decision by how finicky it was to set up and execute.

**Comment by maniarathi** [comment]
Here's a helpful thread on how scientists are doing it today: https://cziscience.slack.com/archives/CCTA8DF1T/p1594830704081300

**Comment by brianraymor** [comment]
Removing from the _Launch the cellxgene.cziscience.com data portal with migrated datasets_ M1 epic. It's not required for M1 launch, but is required to enable download stories in M2.

**Comment by brianraymor** [comment]
Per the September 22 Refinement, moving to the Product Backlog to complete the in-progress epic.

**Comment by brianraymor** [comment]
@mckinsel - I'm not certain how to stage this issue since there are pending questions in the top-level summary comment. 

I'm in the process of defining smaller slices for the upload stories - _Publishers want to upload a .h5ad|.loom|.rds dataset to a private collection from dropbox|google drive|local machine_ - so this issue could be a blocking dependency on  _Publishers want to upload a .rds dataset to a private collection from dropbox._ but I'm also unclear on the plans for validation - moving from the required use of the cellxgene CLI prior to upload to upload of all formats and validation in the service.

**Comment by brianraymor** [comment]
Closing until self-publication stories return to the roadmap.
