### ISSUE TITLE
Create CICD deployment diagram

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#403]
This is to assist with cleaning up the CICD deployment of Corpora using single-cell-infra. See https://github.com/chanzuckerberg/single-cell-infra/pull/94#issuecomment-648989681. Include in the diagram:
* deployment stages dev, staging, and prod.
* The jobs that start the deployment
* The terraform modules that are used by each stage
* The terraform infra that is shared by each stage
* The aws account associated with each stage
* The chalice apps deployed from Corpora
* The static website deployed from Corpora

**Comment by tihuan** [comment]
Hey @Bento007 ! We're just going through DP tickets now 😄 

Just curious, have you started working on this yet? If yes, how many days do you think it will take to close this ticket out?

Because if the work hasn't started yet, we can actually close this ticket until Infra raises the need for the diagram again

Thank you! 🙏
