### ISSUE TITLE
The portal and cellxgene cookie banners and behavior are almost, but not quite, entirely unlike tea

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#579]
Is there a reason that the experience is not consistent across the product? 

![cellxgene banner.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/2e05f6fb-d324-486c-b299-93a569081e29)

![portal banner.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/ed87a584-de70-4816-8ade-c01ee4abb3fe)

**Comment by pdugan20** [comment]
When @colinmegill and I first discussed this, I believe it was prior to us deprecating Corpora as a distinct brand. Having said that, when we did discuss we opted not to identically implement the banner on the data portal given some of the stylistic differences there.

If we'd like to revisit that decision, and since this will be one of the few pieces of UI that will be used across both the data portal and cellxgene, I'd certainly be happy to discuss how to bring them both closer (if not identically) into alignment.

**Comment by brianraymor** [comment]
In addition, cellxgene appears to disable the UX until the user has made a decision, but the data portal allows a user to ignore the question and click on buttons. The behavior should be consistent.

**Comment by brianraymor** [comment]
I expect to close this issue once more information is available on _OneTrust_.

**Comment by brianraymor** [comment]
Closing per PM triage. Will create a new issue for _onetrust_.
