### ISSUE TITLE
QA feedback for download UX

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#622]
Definition of done:
1. Hide scroll bar in Chrome, FF, and Safari
1. Change download prompt text to: `Select one of the data formats to view its download details`
1. Update `.anndata` to `.h5ad (AnnData v0.7)`
1. Update Data Portal description to:

>The cellxgene data portal is a repository of public, explorable single-cell datasets. If you have a public dataset that you would like hosted on this site, please let us know at cellxgene@chanzuckerberg.com.

From QA:

1. The scrollbar for the curl box is not displayed for all users when a format is selected. 
2. Make sure all other text changes are there!

@ambrosejcarr sees:

![With scrollbar.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/863e61e5-3d15-4f20-904d-ddafbdb27b5e)

but @maniarathi and I see:

![Without scrollbar.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/c3e73ac6-7e48-4c31-873e-fa1185c4d0f0)

Ambrose further comments _there is a scroll bar but I can't use it. I can't see the full URL. I feel the user should be able to see the full URL without copying it._

2. Can the _Select from an above data format to view download details_ text be changed to _Select one of the data formats to view its download details._ @pdugan20 - thoughts?

3. From @bmccandless 

On the main page:

> The cellxgene data portal is a repository of public, explorable single-cell datasets. If you have a public dataset which you would like hosted for visualization on this site, please let us know at cellxgene@chanzuckerberg.com.

I believe "which" should be replaced with "that".  Also, I'd drop the "for visualization" can be dropped because it is also hosted not just for visualization (but also download, and more later).

4. From @bkmartinjr:

Download - it gives me the option of a .anndata file.  AFAIK, there is no such thing (I think it means .h5ad if using the file suffix, or AnnData if using the Python module name).   Probably should follow the convention you use with .rds, and simply say:   .h5ad (AnnData v0.7)

Note from @brianraymor - an [earlier suggestion](https://github.com/chanzuckerberg/single-cell/issues/17#issuecomment-678421109) was:

_In discussing with @mckinsel, for easier recognition, we could be precise and identify both the format name and file extension where it differs such as AnnData (.h5ad)._

**Comment by pdugan20** [comment]
Because we're using a copy link pattern here that renders onHover, that means the scroll behavior is always going to be obscured by the overlay. I'd be fine doubling the height of the codeblock:
<img width="533" alt="Screen Shot 2020-09-24 at 8 00 56 PM" src="https://user-images.githubusercontent.com/1837100/94211924-c154bd00-fea0-11ea-8a35-b2bceacf9cbf.png">

...we could alternatively show the whole thing, but I'd advocate against that based on how long the URL is:
<img width="709" alt="Screen Shot 2020-09-24 at 8 03 27 PM" src="https://user-images.githubusercontent.com/1837100/94212048-1c86af80-fea1-11ea-9016-4808a2a01a7d.png">

If we're going to keep the current onHover behavior, we should probably disable the scroll altogether since the user can't see the scrolled code very well. If we feel like it's important for them to see the full code, we can switch to a different interaction pattern, but this tends to be a fairly common one for code blocks.

As for the copy changes, those all sounds great to me.

**Comment by tihuan** [comment]
I exchanged "estimate me" with "refine me", since we're still deciding on the expected behavior of the code block 😄 

BrianR what's your thought on Pat's comment? Thank you!

**Comment by brianraymor** [comment]
I've asked Ambrose to explain the rationale for his request _user should be able to see the full URL without copying it_ before we pursue a solution. For example - in the DCP, we had the capability to only copy the link to the download matrix so it could be pasted into code.

**Comment by ambrosejcarr** [comment]
@brianraymor You are correct to call me on this and I'll defer to you on the decision. I jumped to an implementation detail while rapidly QAing wednesday night. I also made assumptions that we were meant to be able to scroll because on my browser I was presented with a scroll bar! Here are my thoughts, hopefully they help you and @pdugan20 find the right solution! 

**Why show the URL at all?** I come up with two answers to this question: (a) For a skilled user, the `curl -o` makes it obvious that the command should copied into terminal and executed there, and (b) by showing the URL, the user can confirm that they have what they were supposed to. 

Now, when I copied it I was confused because I copied a 3 line URL but pasted a massive behemoth into my console. Was that right? Probably, because the thing I downloaded matched. Nevertheless, I know that you both agree that if there are simple solutions we should try to avoid confusion. 

Unfortunately I think @pdugan20 is correct; the full URL is too much text to put into the window. What about putting <URL truncated> or something similar on the modal to make it clear that: (a) user should not be trying to scroll, and (b) we're only showing you part of the URL; you're going to have to trust us for the full thing (which is fine, in my opinion).

**Comment by bkmartinjr** [comment]
I am with @ambrosejcarr - I _really_ wanted to see the URL before I trusted it.

At the risk of suggesting bad solutions, have you considered just adding an "expand" icon/button that would switch modes between the default (obscure, copy-on-click) mode and something that is shows the entire URL?

**Comment by brianraymor** [comment]
Well - I copied and pasted to a terminal window and did not hit <return> until I examined the script. Frankly, why would I trust some text shown me on a web site versus what was actually pasted into the clipboard?

**Comment by tihuan** [comment]
I also examine the command before I hit `return` 😆 But expand to show the full command sounds like a good middleground and should be a low lift fix too, assuming it still provides good UX?

Alternatively we could also replace the code block with a "Copy cURL command" button, so users are forced to examine the copied command that way?

**Comment by tihuan** [comment]
@brianraymor following up on this one to see what approach we wanna go with 😃 Thank you!

**Comment by brianraymor** [comment]
1. No changes to the size of the box for the curl preview. I'd prefer not to prematurely optimize the experience.
2. Disable scrollbar since we're using the overlay

**Comment by tihuan** [comment]
Thanks so much, @brianraymor ! Just added the definition of done to the ticket and estimated this as a 0.5 point, since we're just hiding the scroll bar!

For the UX concern, do we need to collect user feedback to see what they think? Do we need Alex's involvement here? Thank you!

**Comment by brianraymor** [comment]
Per my earlier comments - see[ pastejacking](https://github.com/dxa4481/Pastejacking) or [You can't trust ...](https://nakedsecurity.sophos.com/2016/05/26/why-you-cant-trust-things-you-cut-and-paste-from-web-pages/)

> The simplest way to do that is to paste anything you copy from a web page into something that can’t run commands, like NOTEPAD or TextEdit and examine it first.

**Comment by brianraymor** [comment]
@tihuan - your definition of done is incomplete. There are also text changes required.

**Comment by tihuan** [comment]
Ah thanks for pointing that out, Brian! I'm cooking now will add the text change stuff later and remove the refine me label!

**Comment by pdugan20** [comment]
Thanks for helping out here Timmy :)

**Comment by tihuan** [comment]
Ready for QA now!

https://cellxgene.dev.single-cell.czi.technology/

Thank you!

**Comment by brianraymor** [comment]
This appears correct to me, but Arathi and I never saw the scrollbar. @ambrosejcarr - scrollbar gone for you?

**Comment by ambrosejcarr** [comment]
Yep, scroll bar is gone. Thanks!

**Comment by tihuan** [comment]
Thanks both! Moved to "Ready for Prod"!
