### ISSUE TITLE
Dataset name changes after refresh during upload

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#818]
## Describe the bug
After selecting a dataset to upload from dropbox, the dataset column shows the name of the file. After refreshing that page, the dataset column shows the uuid of the dataset.

## To Reproduce
1. create collection
2. add a dataset using dropbox finder.
3. The name of the file will be in the dataset column.
4. Refresh the page
5. The UUID of the dataset will be in the dataset column

## Expected behavior
Either the name should be the UUID or the file name. The name should remain consistent even after the refresh.

**Comment by tihuan** [comment]
Hi Trent! Thanks so much for filing the bug!

It is the expected behavior and a compromise that PM and UX are taking for now :ok_hand: 

The reason is that when a user selects a file from Dropbox Chooser, the selected file is saved in the JS memory, so if a user refreshes the page, that filename is gone and therefore we fall back to showing the datasetId!
