### ISSUE TITLE
Cancelled uploads continue to completion and appear in the collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#849]
@brianraymor commented on [Mon Jan 25 2021](https://github.com/chanzuckerberg/single-cell/issues/113)

I created a collection. I cancelled multiple `NaN` uploads. The uploads disappeared from the list. Then I allowed a `Nan` to continue to completion. The final collection shows multiple `NaN`(s) in the list. 

![Screen Shot 2021-01-25 at 10.58.25 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/c0066395-1e89-44b4-85a8-b0e3dc2d42ec)

**Comment by tihuan** [comment]
Hmm yeah it seems like a `CANCEL_PENDING` dataset somehow gets back to `CONVERTING` after a while. Might need BE to take a look 🙏! Thank you!

[CANCEL_PENDING]
![Screen Shot 2021-01-25 at 12.30.57 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/f5b3acb0-20d7-4740-8ec1-b105fabee269)

Bug: [UPLOADED] -- expected behavior is either staying as `CANCEL_PENDING` or `CANCELLED`, instead we get `UPLOADED`
![Screen Shot 2021-01-25 at 12.45.27 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/125a9620-6bde-4b25-9884-48625d228500)
