### ISSUE TITLE
bug(test password): Remove Test pass word from frontend test code

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#900]
## Describe the bug
Remove the plain text test user password from the repo. This value should be import using AWS secrets manager.

https://github.com/chanzuckerberg/cellxgene/blob/main/client/__tests__/e2e/cellxgeneActions.js#L319-321

## Additional context
The AWS secret `corpora/backend/dev/auth0-secret['test_account_password']` can be used for test, dev and staging.
The user name for the backend can be found here https://github.com/chanzuckerberg/corpora-data-portal/blob/5053b610e82b1d359f53f23714f9fee9e507663e/tests/functional/backend/corpora/test_api.py#L35

Timmy: Once we retrieve the secret, we can pass it as env variable in the command to run the test, similar to `HEADLESS=false`!

**Comment by seve** [comment]
In order to meet the high prio needs, I'll be disabling auth and auth-related integration tests on both cellxgene and data portal.  This will include deleting the Auth0 accounts themselves.

Will be deferring the reintroduction of auth tests in a separate issue(todo: link here), so we can elegantly meet our auth needs.

**Comment by seve** [comment]
PRs are merged and accounts are deleted, we're good to close 👍
